AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for lambda

Resources:
  Get:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: build/handlers/knights/get/app.handle
      Runtime: nodejs14.x
      Timeout: 30
      MemorySize: 1028
      Events:
        HealthCheck:
          Type: Api
          Properties:
            Path: /knights
            Method: get
  GetById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: build/handlers/knights/get-by-id/app.handle
      Runtime: nodejs14.x
      Timeout: 30
      MemorySize: 1028
      Events:
        HealthCheck:
          Type: Api
          Properties:
            Path: /knights-by-id/{id}
            Method: get
  Post:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: build/handlers/knights/create/app.handle
      Runtime: nodejs14.x
      Timeout: 30
      MemorySize: 1028
      Events:
        HealthCheck:
          Type: Api
          Properties:
            Path: /knights
            Method: post
  Patch:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: build/handlers/knights/update/app.handle
      Runtime: nodejs14.x
      Timeout: 30
      MemorySize: 1028
      Events:
        HealthCheck:
          Type: Api
          Properties:
            Path: /knights/{id}
            Method: patch

  Delete:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: build/handlers/knights/delete/app.handle
      Runtime: nodejs14.x
      Timeout: 30
      MemorySize: 1028
      Events:
        HealthCheck:
          Type: Api
          Properties:
            Path: /knights/{id}
            Method: delete


  WeaponPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: build/handlers/weapons/app.handle
      Runtime: nodejs14.x
      Timeout: 30
      MemorySize: 1028
      Events:
        HealthCheck:
          Type: Api
          Properties:
            Path: /weapons
            Method: post
